server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring:
  application:
    name: e-comerace-external-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:3002"
              - "http://market.excellencekits.com"
              - "http://adminmarket.excellencekits.com"
              - "http://vendor.excellencekits.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: 
              - "Location" 
      routes:
        - id: market-orchestrator
          uri: lb://market-orchestrator
          predicates:
            - Path=/market-orchestrator/**
        - id: profile
          uri: lb://profile
          predicates:
            - Path=/profile/** 
        - id: customer-profile
          uri: lb://customer-profile
          predicates:
            - Path=/customer-profile/**   
        - id: market-order
          uri: lb://market-order
          predicates:
            - Path=/market-order/**  
        - id: vendor-profile
          uri: lb://vendor-profile
          predicates:
            - Path=/vendor-profile/**              
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: market-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://stg-services.excellencekits.com/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://stg-oauth2.excellencekits.com
jwt:
  auth:
    converter:
      resource-id: web_front_auth
      principal-attribute: preferred_username
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /market-orchestrator/customer/**
