server:
  port: 8032
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring:
  application:
    name: e-comerace-internal-gateway
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  log:
    level: info
    format: json  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://adminmarket.excellencekits.com"
              - "https://market.excellencekits.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: 
              - "Location" 
      routes:
        - id: car-market
          uri: lb://ecom-cars-market
          predicates:
            - Path=/cars-market/**
        - id: properties-market
          uri: lb://ecom-properties-market
          predicates:
            - Path=/properties-market/**           
        - id: furniture-market
          uri: lb://ecom-furniture-market
          predicates:
            - Path=/furniture-market/**
        - id: fashion-market
          uri: lb://ecom-fashion-market
          predicates:
            - Path=/fashion-market/**
        - id: stationary-market
          uri: lb://ecom-stationary-market
          predicates:
            - Path=/stationary-market/**     
        - id: stationary-market
          uri: lb://ecom-stationary-market
          predicates:
            - Path=/stationary-market/**       
        - id: electronics-market
          uri: lb://ecom-electronics-market
          predicates:
            - Path=/ecom-electronics-market/**              
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: market-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://stg-services.excellencekits.com/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://stg-oauth2.excellencekits.com
jwt:
  auth:
    converter:
      resource-id: web_front_auth
      principal-attribute: preferred_username
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /market-orchestrator/customer/**
