server:
  port: 8032
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring:
  application:
    name: e-comerace-internal-gateway
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  log:
    level: info
    format: json  
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "https://adminmarket.excellencekits.com"
              - "https://market.excellencekits.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: 
              - "Location" 
      routes:
        - id: car-market
          uri: lb://e-cars-market
          predicates:
            - Path=/e-cars-market/**
        - id: properties-market
          uri: lb://e-properties-market
          predicates:
            - Path=/e-properties-market/**           
        - id: furniture-market
          uri: lb://e-furniture-market
          predicates:
            - Path=/e-furniture-market/**
        - id: fashion-market
          uri: lb://e-fashion-market
          predicates:
            - Path=/e-fashion-market/**
        - id: stationary-market
          uri: lb://e-stationary-market
          predicates:
            - Path=/e-stationary-market/**     
        - id: stationary-market
          uri: lb://e-stationary-market
          predicates:
            - Path=/e-stationary-market/**       
        - id: electronics-market
          uri: lb://e-electronics-market
          predicates:
            - Path=/e-electronics-market/**              
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: market-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://stg-services.excellencekits.com/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://stg-oauth2.excellencekits.com
jwt:
  auth:
    converter:
      resource-id: web_front_auth
      principal-attribute: preferred_username
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /market-orchestrator/customer/**
