server:
  port: 8032
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring:
  application:
    name: e-comerace-internal-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: 
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://adminmarket.excellencekits.com"
              - "http://market.excellencekits.com"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: 
              - "Location" 
      routes:
        - id: car-market
          uri: lb://car-market
          predicates:
            - Path=/car-market/**
        - id: electronics-market
          uri: lb://electronics-market
          predicates:
            - Path=/electronics-market/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: market-id
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://stg-services.excellencekits.com/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://stg-oauth2.excellencekits.com
jwt:
  auth:
    converter:
      resource-id: web_front_auth
      principal-attribute: preferred_username
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /market-orchestrator/customer/**
