server:
  port: 0
spring:  
  datasource:
    url: jdbc:mysql://hexadb:3306/config-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
