logging:
  level:
    org.springframework: INFO
server:
  port: 8090
  servlet:
    context-path: /configuration
spring:
  application:
    name: configuration
  config:
    import: configserver:http://config.excellencekits.com/
    label: main
  datasource:
    url: jdbc:mysql://hexadb:3306/config-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /configuration/
