server:
  port: 8090
  servlet:
    context-path: /configuration
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411/
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/config-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /configuration/operator/**
      - /configuration/**
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
