server:
  port: 0
  servlet:
    context-path: /onboarding
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://stg-discovery.excellencekits.com:8761/eureka}
services:
  configuration: fastcar-gateway
  user-manager: http://stg-user-maneger.excellencekits.com  
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/onboarding-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info

  kafka:
    bootstrap-servers: stg-kafka.excellencekits.com:9092
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /onboarding/captain/signupBasicProfile
