server:
 port: 9900
config:
  issuer-url: http://localhost:9900
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
