server:
 port: 9900
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://stg-oauth2.excellencekits.com/login/oauth2/code/{registrationId}"
