server:
  port: 9901
  servlet:
    context-path: /user-manager
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring:
  log:
    level: info
    format: json
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://stgauth.excellencekits.com:3306/auth-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://stg-oauth2.excellencekits.com
          audience:
            - notification-service
            - payments-service
            - inventory-service
logging:
  level:
    org:
      springframework:
        security: trace
