server:
  port: 8034
  servlet:
    context-path: /customer-profile
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
services:  
  user-manager: http://stg-user-maneger.excellencekits.com
  imagevault: http://image-vault.excellencekits.com/image-vault/images/
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    unsecured-urls:
      - /profile/save
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/customer-profile-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info
    format: json
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
external-service:
  config:
    - id: userManagement
      host: http://stg-user-maneger.excellencekits.com
      context: /user-manager 
      security: 
        token-url: http://stg-oauth2.excellencekits.com/oauth2/token
        grant-type: client_credentials
        client-id: market-dev-vendor-id
        client-secret: secret
      services:
        - name: createUser
          path: /account/create
        - name: updateUser
          path: /account/
