project:
  name: e-commerce
server:
  port: 8034
  servlet:
    context-path: /customer-profile
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    unsecured-urls:
      - /signup
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/customer-profile-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info
    format: text
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
external-service:
  config:
    - id: userManagement
      host: https://stg-user-maneger.excellencekits.com
      context: /user-manager 
      security: 
        token-url: https://stg-oauth2.excellencekits.com/oauth2/token
        grant-type: client_credentials
        client-id: market-dev-customer-id
        client-secret: secret
      services:
        - name: userDetails
          path: "/account/info/{userId}"
       - name: createUser
          path: "/account/create"
        - name: updateUser
          path: "/account/"   
images-service-config:
  enable: true
  project-base-directory: e-commerce
  server-url: https://image-vault.excellencekits.com/images
  entities:
    - entity: customers  
