server:
  port: 8036
  servlet:
    context-path: /market-order
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
project:
  name: e-commerce
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/ecommerce-order-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info
    format: json
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
external-service:
  config:
    - id: customerprofile
      host: https://marketapi.excellencekits.com/
      context: /customer-profile/
      security: 
        token-url: https://stg-oauth2.excellencekits.com/oauth2/token
        grant-type: token
      services:
        - name: removecart
          path: cart/delete
    - id: marketService
      host: https://marketapi.excellencekits.com/
      context: /market-orchestrator/
      headers:
        - X-context-Header
      security: 
        token-url: https://stg-oauth2.excellencekits.com/oauth2/token
        grant-type: token
      services:
        - name: productVoListDetails
          path: customer/productDetails/vo
        - name: updateItemSoldCount
          path: customer/productDetails/updateItemSoldCount          
    - id: vendorProfileService
      host: https://marketapi.excellencekits.com/
      context: /vendor-profile/
      security: 
        token-url: https://stg-oauth2.excellencekits.com/oauth2/token
        grant-type: token
      services:
        - name: storeLocationService
          path: webhook/storesLocation         
services:  
  imagevault: https://image-vault.excellencekits.com/images/images/
