server:
  port: 8031
  servlet:
    context-path: /market-orchestrator
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
services:  
  user-manager: https://stg-user-maneger.excellencekits.com
  imagevault: https://image-vault.excellencekits.com/image-vault/images/
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    unsecured-urls:
      - /customer/**
      - /dashboard
      - /config/markets
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://stg-oauth2.excellencekits.com
  datasource:
    url: jdbc:mysql://stg-db.excellencekits.com:3306/market-orchestrator-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  log:
    level: info
    format: json
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
markets-config:
  host: http://cgw-e-comerace-internal-gateway:8032/
  markets:
    - electronics-market
custom:
  security:
    expose-unsecured-urls: true
    unsecured-urls:
      - /market-orchestrator/customer/**
