server:
  port: 8030
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
services:  
  user-manager: http://stg-user-maneger.excellencekits.com
spring: 
  zipkin:
    base-url: stg-zipkin.excellencekits.com:9411
  cloud:
    compatibility-verifier:
      enabled: true
  security:
    unsecured-urls:
      - /**
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://stg-oauth2.excellencekits.com
  log:
    level: info
config:
  kafka:
    enabled: true
    producer: true
management:
  zipkin:
    tracing:
      endpoint: stg-zipkin.excellencekits.com:9411/api/v2/spans  
  endpoints:
    web:
      exposure:
        include: '*'
markets-config:
  host: E-COMERACE-INTERNAL-GATEWAY/
  markets:
    - car-market
    - electronics-market
