server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://cloud-discovery:8761/eureka}
  servlet:
    context-path: /notification
spring:
  log:
    level: info
  datasource:
    url: jdbc:mysql://hexadb:3306/notification-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://stg-oauth2.excellencekits.com
          audience:
            - "notification-service1"

  mail:
    host: smtp.gmail.com
    username: elmustafafriri@gmail.com
    password: tyse gyiv tixy jlmm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: stg-kafka.excellencekits.com:9092
config:
  kafka:
    enabled: false
    producer: false
    consumer: false
