server:
  port: 8070
  servlet:
    context-path: /notification
spring:
  log:
    level: info
  datasource:
    url: jdbc:mysql://hexadb:3306/notification-db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: hexa
    password: mwdl
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
  mail:
    host: smtp.gmail.com
    username: elmustafafriri@gmail.com
    password: tyse gyiv tixy jlmm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: hexadb:9092
config:
  kafka:
    enabled: true
    consumer: true
